# Generated by Django 5.1 on 2024-11-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='kam/image/')),
                ('kam_css', models.CharField(default='-', max_length=200, verbose_name='CSS класс')),
            ],
        ),
        migrations.AlterField(
            model_name='kam',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='kam',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
