# Generated by Django 5.1 on 2024-11-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='kam',
            name='price',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
