# Generated by Django 5.1 on 2024-11-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0005_kam_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
