# Generated by Django 5.1 on 2024-11-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0007_reviews_delete_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Otzv',
        ),
    ]
