# Generated by Django 5.1 on 2024-11-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0011_alter_review_created_at_alter_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
