# Generated by Django 5.1 on 2024-11-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0013_new_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
