# Generated by Django 5.1 on 2024-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0015_rev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rev',
            name='content',
        ),
        migrations.RemoveField(
            model_name='rev',
            name='created_at',
        ),
        migrations.AddField(
            model_name='rev',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rev',
            name='featured_images',
            field=models.ImageField(blank=True, upload_to='kam/image/'),
        ),
    ]
