# Generated by Django 5.1 on 2024-11-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0016_remove_rev_content_remove_rev_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rev',
            name='featured_images',
        ),
    ]
