# Generated by Django 5.1 on 2024-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0017_remove_rev_featured_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='rev',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
