# Generated by Django 5.1 on 2024-11-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0020_alter_rev_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rev',
            name='image',
            field=models.ImageField(upload_to='kam/image/'),
        ),
    ]
