# Generated by Django 5.1 on 2024-11-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0021_alter_rev_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rev',
            name='description',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='rev',
            name='image',
            field=models.ImageField(upload_to='kam/image/', verbose_name='Загрузить аватар'),
        ),
        migrations.AlterField(
            model_name='rev',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
