# Generated by Django 5.1 on 2024-11-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0022_alter_rev_description_alter_rev_image_alter_rev_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rev',
            name='image',
            field=models.ImageField(blank=True, upload_to='kam/image/', verbose_name='Загрузить аватар'),
        ),
    ]
