# Generated by Django 5.1 on 2024-11-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0023_alter_rev_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rev',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rev',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kam/image/', verbose_name='Загрузить аватар'),
        ),
    ]
